chore(vite installation guide): add installation guide using pmpm
vuejs/docs pull request #1374
Opened 2021-12-09 17:59 UTC by dammy001

## Description of Problem
I figured out that there's no vite installation guide using PNPM

## Proposed Solution
This PR consists of vite installation guide using PMPM

## Additional Information

2021-12-13 04:06 UTC, skirtles-code requested changes
Thanks for the PR!

I agree this would make a good addition. If you could review and accept my suggested changes I think we can get this merged.

2021-12-13 04:06 UTC, skirtles-code commented on src/guide/installation.md
> +$ pnpm create vite <project-name> --template vue
```suggestion
$ pnpm create vite <project-name> -- --template vue
```

This didn't work for me, testing with pnpm 6.23.1. I had to include an extra `--`, a bit like with npm 7+. The Vite docs seem to show the same thing: https://vitejs.dev/guide/#scaffolding-your-first-vite-project

2021-12-13 06:16 UTC, dammy001 commented on src/guide/installation.md
> +Or with PNPM:
Okay. Thanks

2021-12-13 06:28 UTC, dammy001 commented
Done ✅

2021-12-17 05:29 UTC, NataliaTepluhina approved these changes

2021-12-17 05:33 UTC, merged