added dynamic component v-bind note
vuejs/docs pull request #1783
Opened 2022-06-18 03:47 UTC by calebwaldner

## Description of Problem
The documentation states using native HTML elements works with the dynamic `<component>` element, but doesn't state that `v-bind` may not behave as expected.

## Proposed Solution
Added a brief note stating that `v-bind` may not work as expected and also added a brief explanation on why.

## Additional Information
My explanation of why `v-bind` doesn't work was based on how I understood the comments made on this issue. https://github.com/vuejs/core/issues/5020. If my explanation is not accurate I apologize.

2022-06-18 05:53 UTC, tony19 requested changes

2022-06-18 05:53 UTC, tony19 commented on src/guide/essentials/component-basics.md
> +If you're using a native HTML element such as `<component is="'input'">`, using `v-bind` will not work as expected. The compiler doesn't know the element type at build time, therefor it always genera
```suggestion
If you're using a native HTML element such as `<component is="'input'">`, using `v-bind` will not work as expected. The compiler doesn't know the element type at build time. Therefore, it always generates `v-bind` code for a dynamic component, not a native input element.
```

2022-06-18 15:27 UTC, skirtles-code reviewed
Perhaps I'm missing something, but isn't the problem specifically with `v-model`, rather than `v-bind`?

2022-06-18 23:21 UTC, calebwaldner commented
Wow my bad, 100% `v-model`. Fixing

2022-06-18 23:26 UTC, calebwaldner commented
@skirtles-code Sorry about that, did all this late at night, silly mistake. I fixed both the docs and PR description

2022-06-18 23:31 UTC, tony19 requested changes

2022-06-18 23:31 UTC, tony19 commented on src/guide/essentials/component-basics.md
> +If you're using a native HTML element such as `<component is="'input'">`, using `v-model` will not work as expected. The compiler doesn't know the element type at build time, therefor it always gener
```suggestion
If you're using a native HTML element such as `<component is="'input'">`, using `v-model` will not work as expected. The compiler doesn't know the element type at build time. Therefore, it always generates `v-model` code for a dynamic component, not a native input element.
```

2022-06-21 13:41 UTC, calebwaldner commented
I believe this is ready for review. If there is anything I can do to improve this let me know.

2022-06-27 18:35 UTC, skirtles-code commented
I've attempted an alternative way of documenting this in #1807.

I'll keep this PR open while we discuss the best way to proceed.

2022-06-28 13:19 UTC, calebwaldner commented
Agreed, the updated placement of this issue is more appropriate 👍🏼

2022-06-28 13:19 UTC, calebwaldner commented
I'll go ahead and close this issue, thanks for making it happen

2022-06-28 13:19 UTC, closed without merging