Added `withDefaults` to Composition API TypeScript page
vuejs/docs pull request #1942
Opened 2022-08-29 12:28 UTC by NataliaTepluhina

## Description of Problem

Currently, we only mention `withDefaults` on the [API page](https://vuejs.org/api/sfc-script-setup.html#typescript-only-features) but not on the [guide page about Composition API with TypeScript](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props)

## Proposed Solution

Add `withDefaults` as a default option to the guide

## Additional Information

Close #1843

2022-08-31 08:09 UTC, skirtles-code requested changes

2022-08-31 08:09 UTC, skirtles-code commented on src/guide/typescript/composition-api.md
> +Alternatively, you can use currently experimental [Reactivity Transform](/guide/extras/reactivity-transform.html):
```suggestion
Alternatively, you can use the currently experimental [Reactivity Transform](/guide/extras/reactivity-transform.html):
```

2022-09-05 04:35 UTC, NataliaTepluhina commented on src/guide/typescript/composition-api.md
>  ### Props Default Values <sup class="vt-badge experimental" />
That was my concern as well! I wasn't sure if we should remove it (we are still discussing an alternative solution which is experimental) but after your comment, I am more inclined to do so. Removed ✅

2022-09-05 04:35 UTC, NataliaTepluhina commented
@skirtles-code thank you for the review! I have addressed your concerns, could you please take a second look?

2022-09-09 00:48 UTC, skirtles-code approved these changes

2022-09-09 00:48 UTC, merged