Update: watchers.md
vuejs/docs pull request #2069
Opened 2022-11-08 11:00 UTC by JohnnyEvo

Add `Eager Watchers` section to composition side

## Description of Problem

When we are in `composition` option, `Eager watchers` is not mentioned.

## Proposed Solution

Add `Eager watchers` in `composition` option.

## Additional Information

2022-11-08 17:11 UTC, skirtles-code requested changes
Good point, this does need to be covered.

I've provided some feedback on your proposed changes below.

2022-11-08 17:11 UTC, skirtles-code commented on src/guide/essentials/watchers.md
> +  // logic
Maybe use `...`, like the other examples?

```suggestion
  // ...
```

2022-11-08 17:30 UTC, JohnnyEvo commented
Thank you, I considered your review

2022-11-09 20:40 UTC, skirtles-code commented
@JohnnyEvo Thanks for making those changes.

I've just had another read through and I think we now have a problem with the section about `watchEffect()`. The wording of that section no longer makes sense now that it's preceded by this new section about `immediate: true`.

Would you like to attempt that rewording yourself? If not then I can give it a go.

2022-11-14 09:59 UTC, skirtles-code commented
The problem is that the `watchEffect()` section presents `watchEffect()` as a way to implement eager watchers. It starts with a sentence saying that `watch()` is lazy and then shows how `watchEffect()` is the solution to that problem. It doesn't make sense if it comes immediately after a section all about eager watchers. We're presenting two solutions to the same problem without acknowledging the overlap.

With hindsight I don't think the omission of the section about eager watcher is an oversight. I think it was intentional, with the section about `watchEffect()` being seen as a way to solve the same problem. I still think having a section about eager watchers is a good idea, but we can't have the `watchEffect()` section framed as a solution to a problem we've just solved in the preceding section.

2022-11-14 19:15 UTC, JohnnyEvo commented
I understand the inconsistency. 
We can say that there is an alternative for the lazy watch... but what is the point of having two different ways of doing the same thing? Why choose one or the other?

2023-01-03 22:41 UTC, skirtles-code commented
I've pulled these commits into #2144 and made some changes to the `watchEffect()` section, so that it doesn't seem quite so out of place.

2023-01-03 22:41 UTC, closed without merging