Added a warning regarding async setup
vuejs/docs pull request #2105
Opened 2022-11-23 10:54 UTC by NataliaTepluhina

## Description of Problem

Currently we don't have any information in the docs regarding the fact that normally, `setup()` should always be called synchronously. This raises questions from users who try to call `async setup()` and fail.

## Proposed Solution

Add a warning to `setup()` docs

## Additional Information

Close #1032

2022-11-30 03:59 UTC, skirtles-code requested changes
Sorry for the delay.

We already have a 'tip' just before this 'warning'. Do you think we could remove the two containers and have them as normal paragraphs instead? I think the words 'Note that' from the earlier paragraph can probably be removed too.

I've made a suggestion about the proposed wording below.

2022-11-30 03:59 UTC, skirtles-code commented on src/api/composition-api-setup.md
> +`setup()` should always be called _synchronously_. The only case when `async setup()` can be used is when the component is a descentand of a [Suspense](../guide/built-ins/suspense.html) component.
```suggestion
`setup()` should return an object _synchronously_. The only case when `async setup()` can be used is when the component is a descendant of a [Suspense](../guide/built-ins/suspense.html) component.
```

2022-12-01 12:26 UTC, NataliaTepluhina commented
@skirtles-code thank you for the review! I've applied the requested changes, could you please take a second look?

2022-12-07 17:16 UTC, skirtles-code approved these changes

2022-12-07 17:17 UTC, merged