Update application.md
vuejs/docs pull request #2138
Opened 2022-12-26 05:03 UTC by Heniker

## Description of Problem
Guide  [Augmenting Global Properties](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties) is hard to find, because it is located under Options API section, while it actually has uses in Composition API as well.

## Proposed Solution
Mention [Augmenting Global Properties](https://vuejs.org/guide/typescript/options-api.html#augmenting-global-properties) under `app.config.globalProperties`.

## Additional Information

2022-12-30 23:37 UTC, skirtles-code requested changes
Good idea.

I suggest adding the TS badge at the end (see below). I'm not sure how consistent we are with this, but links to TS-specific topics are supposed to have that badge.

2022-12-30 23:37 UTC, skirtles-code commented on src/api/application.md
> +- **See also:** [Guide - Augmenting Global Properties](/guide/typescript/options-api.html#augmenting-global-properties)
```suggestion
- **See also:** [Guide - Augmenting Global Properties](/guide/typescript/options-api.html#augmenting-global-properties) <sup class="vt-badge ts" />
```

2022-12-31 07:34 UTC, Heniker commented
Yea, that makes sense. Accepted change.

2023-01-01 19:03 UTC, skirtles-code approved these changes

2023-01-01 19:03 UTC, merged