Sytles: Responsive for Preference Switch
vuejs/docs pull request #2285
Opened 2023-03-12 13:34 UTC by sergiopani

Changing the responsive styles from the preferenced options on less 960px of screen.

Before:

<img width="355" alt="Captura de Pantalla 2023-03-12 a las 14 29 30" src="https://user-images.githubusercontent.com/42542864/224548059-f5bc835b-75d4-49c8-9b03-bc6968260053.png">

Now:

<img width="302" alt="Captura de Pantalla 2023-03-12 a las 14 29 06" src="https://user-images.githubusercontent.com/42542864/224548089-48d0a537-6fb8-474f-b300-f7cdb93fbfbc.png">

2023-03-14 13:34 UTC, skirtles-code requested changes
Thanks for the improvement. This does look better.

I've made some suggestions below. If you could address those then I think we can merge this.

2023-03-14 13:34 UTC, skirtles-code commented on .vitepress/theme/components/PreferenceSwitch.vue
> +    padding:0px 1em;
```suggestion
@media(max-width: 959px){
  .switch-container {
    padding: 0 1em;
```

I've tweaked a few things:
1. Spaces after colons.
2. No units for `0`.
3. `max-width: 960px` leads to an inconsistency when the viewport is exactly 960px wide. I've changed the media query to use 959px instead.

2023-03-14 13:34 UTC, skirtles-code commented on package-lock.json
This file shouldn't be included in the PR.

2023-03-15 19:38 UTC, skirtles-code requested changes

2023-03-15 19:38 UTC, skirtles-code commented on .vitepress/theme/components/PreferenceSwitch.vue
> +    padding:0 1em;
This is still missing the spaces after the colons:

```suggestion
@media(max-width: 959px){
  .switch-container {
    padding: 0 1em;
```

2023-03-15 19:38 UTC, skirtles-code commented on package-lock.json
`package-lock.json` needs to be removed from the PR.

2023-03-15 20:40 UTC, sergiopani commented
At least! As a first-time contributor, I was not familiar with the process of accepting changes made to my code on github. I appreciate your patience!

2023-03-18 19:23 UTC, skirtles-code approved these changes
Looks good to me. Thanks.

2023-03-18 19:25 UTC, merged