docs: fix typo - count should be model
vuejs/docs pull request #2749
Opened 2024-03-13 13:30 UTC by EtherNoteWorld

## Description of Problem
When I read the documentation, I am unclear about the source of this count.
## Proposed Solution

## Additional Information

2024-03-13 13:52 UTC, brc-dd approved these changes

2024-03-13 14:00 UTC, brc-dd commented
Actually, the name doesn't matter in parent component. It can be `count`, `foo`, `bar` or anything else. This change might be bit confusing for new users as they might think that the variable name should be `model` too. I'm fine with either one though.

2024-03-13 14:51 UTC, AloisSeckar commented
I object against this chage as it goes against clean code principles. Naming the variable `model` makes sense inside the component itself, because there it has clear purpose - it _"models the actual data value for this component"_. But from parent's perspective you want to know, what data you are passing to your child, what they represent. Therefore `count` makes sense, if you are displaying, let's say amount items in shoping cart, but `model` is nothing. If you use two child components, will you name your variables `model1` and `model2`? How about having ten children?

But maybe we should make clearer, why `count` is used. I will think about some wording, if noone else does.

2024-03-13 18:40 UTC, bencodezen commented
Agreed with @AloisSeckar. I'll propose some changes in the PR to accommodate the general momentum we seem to be heading on.

2024-03-13 18:41 UTC, bencodezen requested changes
Naming the model `model` can lead to future confusion. Suggesting changes shortly.

2024-03-13 18:44 UTC, bencodezen commented on src/guide/components/v-model.md
> +<Child v-model="model" />
```suggestion
<Child v-model="countModel" />
```

2024-03-13 18:45 UTC, bencodezen commented on src/guide/components/v-model.md
> +<Child v-model="model" />
@EtherNoteWorld Can you update the PR to update the variables so that it reflects `countModel` rather than just `model`?

2024-03-17 13:52 UTC, NataliaTepluhina approved these changes

2024-03-17 13:52 UTC, merged