feat(guide/computed): add previous to computed
vuejs/docs pull request #3001
Opened 2024-09-06 16:26 UTC by ferferga

This was shipped silently in Vue 3.4. See [PR](https://github.com/vuejs/core/pull/9497)

2024-09-26 15:15 UTC, NataliaTepluhina requested changes

2024-09-26 15:15 UTC, NataliaTepluhina commented on src/guide/essentials/computed.md
> +      if (this.count >= 3) {
**question**: should this be `<=3` according to the explanation above?

2024-09-26 15:15 UTC, NataliaTepluhina commented on src/guide/essentials/computed.md
> +  if (count.value >= 3) {
Same note about <=3

2024-09-27 09:05 UTC, ferferga commented
Good catch @NataliaTepluhina! Changed the logic a few times while working on this because I wasn't convinced in the examples that I was providing and completely missed this!

I also added the closing `</script>` tag that was missing from one of the Composition API's examples in my last commit.

2024-09-27 16:16 UTC, NataliaTepluhina commented on src/guide/essentials/computed.md
> +        if (this.count >= 3) {
```suggestion
        if (this.count <= 3) {
```

2024-09-27 16:16 UTC, NataliaTepluhina commented on src/guide/essentials/computed.md
> +    if (count.value >= 3) {
```suggestion
    if (count.value <= 3) {
```

2024-09-27 16:17 UTC, NataliaTepluhina commented
Thank you @ferferga! I've updated also the examples for writable computeds and I think we're good to go now

2024-09-27 16:20 UTC, merged